# Generated by Django 3.0.7 on 2020-06-19 13:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='audio_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mac', models.CharField(max_length=1000)),
                ('file_au', cloudinary.models.CloudinaryField(max_length=255, verbose_name='audio')),
            ],
        ),
    ]
