# Generated by Django 3.0.7 on 2020-06-19 14:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200619_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_files',
            name='file_au',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
